import { ArrowRight, Copy, ExternalLink, Image as ImageIcon, Link2, Loader2, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { linkFromUrl, readLocalLinks, removeLocalLink, saveLocalLink, type LocalImageLink, verifyImageUrl } from "@/lib/localLinks";
import { toast } from "sonner";

function readableSize(bytes: number) { if (!bytes) return "رابط مستورد"; if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }

export default function MyLinks() {
  const [links, setLinks] = useState<LocalImageLink[]>(() => readLocalLinks());
  const [oldLink, setOldLink] = useState("");
  const [checking, setChecking] = useState(false);
  const [failedPreviews, setFailedPreviews] = useState<Set<string>>(() => new Set());
  const copyLink = async (link: LocalImageLink) => { try { await navigator.clipboard.writeText(link.publicUrl); toast.success("تم نسخ رابط الصورة."); } catch { toast.error("تعذر النسخ تلقائيًا. افتح الصورة ثم انسخ الرابط يدويًا."); } };
  const deleteLink = (publicId: string) => { setLinks(removeLocalLink(publicId)); setFailedPreviews(current => { const next = new Set(current); next.delete(publicId); return next; }); toast.success("تم حذف الرابط من هذا الجهاز."); };
  const saveOldLink = async () => {
    const link = linkFromUrl(oldLink);
    if (!link) { toast.error("ألصق رابط صورة صحيحًا ينتهي بمعرّف الرابط."); return; }
    setChecking(true);
    try { await verifyImageUrl(link.publicUrl); setLinks(saveLocalLink(link)); setOldLink(""); toast.success("تم التحقق من الصورة وإضافتها إلى روابطي."); }
    catch (error) { toast.error(error instanceof Error ? error.message : "تعذر التحقق من الصورة."); }
    finally { setChecking(false); }
  };
  const markPreviewFailed = (publicId: string) => setFailedPreviews(current => new Set(current).add(publicId));

  return <div className="page-enter min-h-screen w-full overflow-x-hidden bg-[#121212] px-5 py-10 text-white"><div className="mx-auto w-full max-w-6xl min-w-0"><header className="flex flex-col items-start justify-between gap-5 border-b border-white/10 pb-8 sm:flex-row sm:items-end"><div className="min-w-0"><Link href="/" className="inline-flex max-w-full items-center gap-2 text-sm font-bold text-white/60 hover:text-white"><ArrowRight className="h-4 w-4 shrink-0" /> العودة إلى Yazin-link</Link><h1 className="display-font mt-5 text-5xl font-semibold tracking-[-0.07em]">روابطي</h1><p className="mt-3 max-w-xl text-white/55">سجل خاص بهذا الجهاز. لا تحتاج إلى إنشاء حساب؛ الروابط التي تنشئها هنا محفوظة في متصفحك فقط.</p></div><a href="/#tool" className="rounded-full bg-[#a8f2c3] px-5 py-3 text-sm font-black text-[#16231c] hover:bg-[#f7f6ef]">إنشاء رابط جديد</a></header>
    <section className="mt-7 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-2 text-sm font-black text-[#a8f2c3]"><Plus className="h-4 w-4" /> أضف رابطًا سابقًا</div><p className="mt-2 text-sm leading-6 text-white/55">نتحقق من أن الرابط يفتح صورة فعلية قبل إضافته إلى القائمة.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row" dir="ltr"><input value={oldLink} onChange={event => setOldLink(event.target.value)} placeholder="https://your-domain/i/abc123" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/30 px-3 py-3 text-sm text-white outline-none placeholder:text-white/25 focus:border-[#a8f2c3]" /><button disabled={checking} onClick={() => void saveOldLink()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#f7f6ef] px-4 py-3 text-sm font-black text-[#151515] hover:bg-[#a8f2c3] disabled:opacity-50">{checking && <Loader2 className="h-4 w-4 animate-spin" />}{checking ? "جارٍ التحقق…" : "إضافة الرابط"}</button></div></section>
    {links.length ? <div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{links.map(link => <article key={link.publicId} className="overflow-hidden rounded-3xl border border-white/10 bg-white/[0.035]">{failedPreviews.has(link.publicId) ? <div className="flex aspect-[16/10] flex-col items-center justify-center bg-black px-6 text-center"><ImageIcon className="h-8 w-8 text-[#ffa8b7]" /><p className="mt-3 text-sm font-bold">لا يمكن معاينة هذه الصورة</p><p className="mt-1 text-xs leading-5 text-white/45">قد يكون الرابط قديمًا أو لا يقدّم ملف صورة مباشرة.</p></div> : <a href={link.publicUrl} target="_blank" rel="noreferrer" className="block aspect-[16/10] overflow-hidden bg-black"><img src={link.publicUrl} alt={link.filename} className="h-full w-full object-cover transition duration-300 hover:scale-105" onError={() => markPreviewFailed(link.publicId)} /></a>}<div className="p-5"><p className="truncate font-bold">{link.filename}</p><p className="mt-1 text-xs text-white/45">{readableSize(link.bytes)} · {new Date(link.createdAt).toLocaleDateString("ar-EG")}</p><div className="mt-5 grid grid-cols-3 gap-2"><button onClick={() => void copyLink(link)} className="inline-flex items-center justify-center rounded-xl bg-[#f7f6ef] py-2.5 text-[#151515] hover:bg-[#a8f2c3]" aria-label="نسخ الرابط"><Copy className="h-4 w-4" /></button><a href={link.publicUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-xl border border-white/15 text-white hover:border-[#a8f2c3] hover:text-[#a8f2c3]" aria-label="فتح الصورة"><ExternalLink className="h-4 w-4" /></a><button onClick={() => deleteLink(link.publicId)} className="inline-flex items-center justify-center rounded-xl border border-[#ffa8b7]/30 text-[#ffa8b7] hover:bg-[#ffa8b7] hover:text-[#151515]" aria-label="حذف الرابط"><Trash2 className="h-4 w-4" /></button></div></div></article>)}</div> : <div className="mt-10 rounded-[28px] border border-dashed border-white/15 bg-white/[0.025] px-6 py-20 text-center"><Link2 className="mx-auto h-10 w-10 text-[#a8f2c3]" /><h2 className="display-font mt-5 text-3xl font-semibold">لا توجد روابط محفوظة بعد</h2><p className="mx-auto mt-3 max-w-md leading-7 text-white/55">أول رابط تنشئه من هذه الأداة سيظهر هنا تلقائيًا على هذا الجهاز.</p><a href="/#tool" className="mt-7 inline-flex rounded-full bg-[#f7f6ef] px-5 py-3 text-sm font-black text-[#151515] hover:bg-[#a8f2c3]">ارفع أول صورة</a></div>}</div></div>;
}
