import { Check, Copy, Link2, Pencil, Trash2, X } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { readLocalLinks, removeLocalLink, renameLocalLink, type LocalImageLink } from "@/lib/localLinks";
import { toast } from "sonner";

function formattedDate(value: string) { return new Date(value).toLocaleDateString("ar-EG", { day: "numeric", month: "short", year: "numeric" }); }

export default function MyLinks() {
  const [links, setLinks] = useState<LocalImageLink[]>(() => readLocalLinks());
  const [editingId, setEditingId] = useState<string | null>(null);
  const [draftName, setDraftName] = useState("");

  const copyLink = async (link: LocalImageLink) => { try { await navigator.clipboard.writeText(link.publicUrl); toast.success("تم نسخ الرابط."); } catch { toast.error("تعذر النسخ تلقائيًا؛ انسخ الرابط يدويًا."); } };
  const deleteLink = (publicId: string) => { setLinks(removeLocalLink(publicId)); toast.success("تم حذف الرابط من هذا الجهاز."); };
  const startRename = (link: LocalImageLink) => { setEditingId(link.publicId); setDraftName(link.filename); };
  const saveRename = (publicId: string) => { const next = renameLocalLink(publicId, draftName); setLinks(next); setEditingId(null); toast.success("تم تعديل اسم الرابط."); };

  return <div className="page-enter min-h-screen w-full overflow-x-hidden bg-[#121212] px-5 py-10 text-white"><div className="mx-auto w-full max-w-4xl min-w-0"><header className="flex flex-col gap-6 border-b border-white/10 pb-8 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-white/60 hover:text-white">العودة إلى Yazin-link</Link><h1 className="display-font mt-5 text-4xl font-semibold tracking-[-0.065em] sm:text-5xl">آخر الروابط</h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/50">تُحفظ هذه القائمة على جهازك فقط.</p></div><Link href="/#tool" className="w-fit rounded-full bg-[#a8f2c3] px-4 py-2.5 text-sm font-black text-[#16231c] hover:bg-[#f7f6ef]">رابط جديد</Link></header>
    {links.length ? <div className="mt-7 space-y-3">{links.map(link => <article key={link.publicId} className="rounded-2xl border border-white/10 bg-white/[0.035] p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">{editingId === link.publicId ? <div className="flex min-w-0 flex-1 items-center gap-2"><input value={draftName} onChange={event => setDraftName(event.target.value)} maxLength={120} autoFocus className="min-w-0 flex-1 rounded-xl border border-[#a8f2c3]/50 bg-black/30 px-3 py-2 text-right text-sm text-white outline-none" /><button onClick={() => saveRename(link.publicId)} className="rounded-xl bg-[#a8f2c3] p-2 text-[#16231c] hover:bg-[#f7f6ef]" aria-label="حفظ الاسم"><Check className="h-4 w-4" /></button><button onClick={() => setEditingId(null)} className="rounded-xl border border-white/15 p-2 text-white/60 hover:text-white" aria-label="إلغاء التعديل"><X className="h-4 w-4" /></button></div> : <div className="min-w-0 flex-1"><p className="truncate font-bold text-white">{link.filename}</p><p className="mt-1 text-xs text-white/40">{formattedDate(link.createdAt)}</p><p dir="ltr" className="mt-2 truncate text-xs text-[#a8f2c3]/75">{link.publicUrl}</p></div>}<div className="grid shrink-0 grid-cols-3 gap-2"><button onClick={() => void copyLink(link)} className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-[#f7f6ef] text-[#151515] hover:bg-[#a8f2c3]" aria-label="نسخ الرابط"><Copy className="h-4 w-4" /></button><button onClick={() => startRename(link)} className="inline-flex h-10 w-10 items-center justify-center rounded-xl border border-white/15 text-white/70 hover:border-[#a8f2c3] hover:text-[#a8f2c3]" aria-label="تعديل الاسم"><Pencil className="h-4 w-4" /></button><button onClick={() => deleteLink(link.publicId)} className="inline-flex h-10 w-10 items-center justify-center rounded-xl border border-[#ffa8b7]/30 text-[#ffa8b7] hover:bg-[#ffa8b7] hover:text-[#151515]" aria-label="حذف الرابط"><Trash2 className="h-4 w-4" /></button></div></div></article>)}</div> : <div className="mt-10 rounded-[28px] border border-dashed border-white/15 bg-white/[0.025] px-6 py-20 text-center"><Link2 className="mx-auto h-10 w-10 text-[#a8f2c3]" /><h2 className="display-font mt-5 text-3xl font-semibold">لا توجد روابط حديثة</h2><p className="mx-auto mt-3 max-w-md leading-7 text-white/55">أنشئ رابطًا لصورة وسيظهر هنا تلقائيًا.</p><Link href="/#tool" className="mt-7 inline-flex rounded-full bg-[#f7f6ef] px-5 py-3 text-sm font-black text-[#151515] hover:bg-[#a8f2c3]">أنشئ أول رابط</Link></div>}</div></div>;
}
